; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 任務 3：請在此修正串口監視器波特率，解決亂碼問題
; monitor_speed = 

; 任務 2：請在此加入 bblanchon/ArduinoJson 依賴
lib_deps =

; 任務 3：建立 [env:release] 環境並提高燒錄速度
